version: '3'

services:
  mongodb-service:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: pfmtodouser
      MONGO_INITDB_ROOT_PASSWORD: p4ssw0rd
      ME_CONFIG_MONGODB_ADMINUSERNAME: pfmtodouser
      ME_CONFIG_MONGODB_ADMINPASSWORD: p4ssw0rd
    volumes:
      - ./data:/data/db
  
  website:
    build: .
    volumes: 
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - mongodb-service
